package com.aliayali.model.analysis

enum class MarketReason {
    USD_SIGNIFICANT_INCREASE,
    USD_INCREASE,
    USD_SIGNIFICANT_DECREASE,
    USD_DECREASE,
    USD_MINOR_CHANGE,

    GOLD_18K_SIGNIFICANT_INCREASE,
    GOLD_18K_INCREASE,
    GOLD_18K_SIGNIFICANT_DECREASE,
    GOLD_18K_DECREASE,
    GOLD_18K_MINOR_CHANGE,

    GOLD_OUNCE_SIGNIFICANT_INCREASE,
    GOLD_OUNCE_INCREASE,
    GOLD_OUNCE_SIGNIFICANT_DECREASE,
    GOLD_OUNCE_DECREASE,
    GOLD_OUNCE_MINOR_CHANGE,

    CRYPTO_STRONG_POSITIVE,
    CRYPTO_MODERATE_POSITIVE,
    CRYPTO_WEAK_POSITIVE,
    CRYPTO_STRONG_NEGATIVE,
    CRYPTO_MODERATE_NEGATIVE,
    CRYPTO_WEAK_NEGATIVE,
    CRYPTO_MIXED,

    LOCAL_STRONG_POSITIVE,
    LOCAL_STRONG_NEGATIVE,
    LOCAL_MODERATE_POSITIVE,
    LOCAL_MODERATE_NEGATIVE,
    LOCAL_WEAK,

    BTC_TREND_RISING,
    BTC_TREND_FALLING,
    BTC_TREND_STABLE,
}